name: Build and Publish on Dispatch
on: workflow_dispatch
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      WANIKANI_API_TOKEN: ${{ secrets.WANIKANI_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache WaniKani API
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.wanikani
          key: wanikani-${{ runner.os }}-${{ github.run_id }}
          restore-keys: wanikani-${{ runner.os }}-
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Build Next.js App
        run: "npm run build"
      - name: Export Static HTML
        run: "npm run export"
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: new-bachmacintosh-com
          directory: "./out"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
