name: Tests (PR)
on:
  pull_request_target:
    types: [labeled, unlabeled, synchronize]
permissions:
  actions: none
jobs:
  run-tests:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Check Safe to Test
        if: "!contains(github.event.pull_request.labels.*.name, 'safe to test') && !contains(github.event.pull_request.labels.*.name, 'dependencies')"
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Build Next.js App
        run: "npm run build:ci"
      - name: Export Static HTML
        run: npm run export
