name: Tests (PR)
on:
  pull_request_target:
    types: [labeled, unlabeled, synchronize]
permissions:
  actions: none
jobs:
  run-tests:
    name: Test Pull Request
    runs-on: ubuntu-latest
    env:
      WANIKANI_API_TOKEN: ${{ secrets.WANIKANI_API_TOKEN }}
    steps:
      - name: Check Safe to Test
        if: "!contains(github.event.pull_request.labels.*.name, 'safe to test') && !contains(github.event.pull_request.labels.*.name, 'dependencies')"
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This Pull Request has not been labeled as Safe to Test yet.')
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Check for Version Bump
        uses: bachmacintosh/need-npm-package-version-bump@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache WaniKani API
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.wanikani
          key: ${{ runner.os }}-wanikani-${{ hashFiles('**/.wanikani') }}
          restore-keys: |
            ${{ runner.os }}-wanikani-
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Build Next.js App
        run: "npm run build"
